---
- name: The Primary macOSa Playbook
  hosts: macos
  connection: local
  become: no

  pre_tasks:

    - name: Include default variables
      include_vars:
        dir: vars
      tags: [ always ]

    - name: Include user-supplied variables
      include_vars:
        dir: user/vars
        ignore_files: [ ".keep", ".DS_Store" ]
      tags: [ always ]

    - name: Get a list of all user-supplied pre tasks to include
      find:
        paths: "{{ playbook_dir }}/user/tasks/pre"
        patterns: "*.yml"
      register: user_pre_tasks
      changed_when: false
      tags: [ mymacosa ]

    - name: Include user-supplied pre tasks
      include_tasks: "{{ user_pre_task_file.path }}"
      with_items: "{{ user_pre_tasks.files }}"
      loop_control:
        loop_var: "user_pre_task_file"
      tags: [ mymacosa ]

    - name: Ensure an initial .bash_profile is present
      lineinfile:
        dest: "/Users/{{ ansible_user_id }}/.bash_profile"
        create: yes
        line: "# macOSa manages a good deal of this file, you probably don't want to edit in here directly"
        insertbefore: BOF
      tags: [ always ]

  roles:

    - { role: homebrew, when: "'homebrew' in include_macosa_roles", tags: [ homebrew ] }
    - { role: xenv, when: "'xenv' in include_macosa_roles", tags: [ xenv ] }
    - { role: docker-for-mac, when: "'docker-for-mac' in include_macosa_roles", tags: [ docker-for-mac, docker ] }
    - { role: browsers, when: "'browsers' in include_macosa_roles", tags: [ browsers ] }
    - { role: aws, when: "'aws' in include_macosa_roles", tags: [ aws ] }
    - { role: user, when: "'user' in include_macosa_roles", tags: [ user ] }
    - { role: system, when: "'system' in include_macosa_roles", tags: [ system ] }

  tasks:

    - name: Get a list of all user-supplied post tasks to include
      find:
        paths: "{{ playbook_dir }}/user/tasks/post"
        patterns: "*.yml"
      register: user_post_tasks
      changed_when: false
      tags: [ mymacosa ]

    - name: Include user-supplied post tasks
      include_tasks: "{{ user_post_task_file.path }}"
      with_items: "{{ user_post_tasks.files }}"
      loop_control:
        loop_var: "user_post_task_file"
      tags: [ mymacosa ]
