---

- name: Make sure .bash_profile is setup
  lineinfile:
    dest: ~/.bash_profile
    create: yes
    line: "{{ item }}"
    insertbefore: BOF
  with_items:
    - "[[ -s ~/.bashrc ]] && source ~/.bashrc"
    - "[[ -s ~/.profile ]] && source ~/.profile"
    - "[[ -s ~/.bash_aliases ]] && source ~/.bash_aliases"
    - "export PATH=/usr/local/bin:/usr/local/sbin:~/.macosa/bin:~/.macosa/user/bin:$PATH"
  tags: [ dotfiles ]

- name: Copy dotfile blocks to ~/
  blockinfile:
    marker: "# {mark} MacOSa managed block"
    dest: "~/{{ item.split('/')[-1] }}"
    create: yes
    block: "{{ lookup('file', item) }}"
    insertbefore: BOF
  when: "(item.split('/')[-1] != '.keep')"
  with_fileglob:
    - "{{ playbook_dir }}/user/blocks/dotfiles/.*"
  tags: [ dotfiles ]

- name: Get current account avatar
  command: >
    dscl . read ~/ Picture
  register: "current_account_avatar"
  when: "account.avatar_path != None"
  changed_when: false
  tags: [ avatar ]

- name: Set account avatar
  command: >
    {{ playbook_dir }}/bin/macosa_setaccountavatar {{ account.avatar_path }}
  when: "(account.avatar_path != None) and ('{{ account.avatar_path }}' not in '{{ current_account_avatar.stdout }}')"
  tags: [ avatar ]

- name: Ensure .ssh directory exists.
  file:
    dest: "~/.ssh"
    mode: 0700
    state: directory
  tags: [ ssh ]

- name: Copy ssh files to ~/.ssh
  synchronize:
    src: "{{ item }}"
    dest: "~/.ssh/{{ item.split('/')[-1] }}"
  when: "item.split('/')[-1] != '.keep'"
  with_fileglob:
    - "{{ playbook_dir }}/user/files/.ssh/*"
  tags: [ ssh ]
