---

- name: Make sure .bash_profile is set up
  blockinfile:
    marker: "# {mark} MacOSa managed block bash_profile_init"
    dest: "/Users/{{ ansible_user_id }}/.bash_profile"
    create: yes
    block: |
      [[ -s ~/.bash_aliases ]] && source ~/.bash_aliases
      if [ -x /usr/libexec/path_helper ]; then eval `/usr/libexec/path_helper -s`; fi
      if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
        export PATH=/usr/local/bin:$PATH
      fi
      if [[ ":$PATH:" != *":/usr/local/sbin:"* ]]; then
        export PATH=/usr/local/sbin:$PATH
      fi
      export PATH=/Users/{{ ansible_user_id }}/.macosa/bin:/Users/{{ ansible_user_id }}/.macosa/user/bin:$PATH
    insertbefore: BOF
  tags: [ dotfiles ]

- name: Copy dotfile blocks to ~/
  blockinfile:
    marker: "# {mark} MacOSa managed block user"
    dest: "/Users/{{ ansible_user_id }}/{{ item.split('/')[-1] }}"
    create: yes
    block: "{{ lookup('file', item) }}"
    insertafter: '# END MacOSa managed block bash_profile_init'
  when: "(item.split('/')[-1] != '.keep')"
  with_fileglob:
    - "{{ playbook_dir }}/user/blocks/dotfiles/.*"
  tags: [ dotfiles ]

- name: Get current account avatar
  command: >
    dscl . read /Users/{{ ansible_user_id }} Picture
  register: "current_account_avatar"
  when: "account.avatar_path != None"
  changed_when: false
  tags: [ avatar ]

- name: Set account avatar
  command: >
    {{ playbook_dir }}/bin/macosa_setaccountavatar {{ ansible_user_id }} {{ account.avatar_path }}
  become: yes
  when: "(account.avatar_path != None) and (account.avatar_path not in current_account_avatar.stdout)"
  tags: [ avatar ]

- name: Ensure .ssh directory exists.
  file:
    dest: "/Users/{{ ansible_user_id }}/.ssh"
    mode: 0700
    state: directory
  tags: [ ssh ]

- name: Write ssh config
  copy:
    content: "{{ ssh['config'] }}"
    dest: "/Users/{{ ansible_user_id }}/.ssh/config"
    mode: 0600

- name: Write ssh private key files
  copy:
    content: "{{ item.private }}"
    dest: "/Users/{{ ansible_user_id }}/.ssh/{{ item.name }}"
    mode: 0600
  with_items: "{{ ssh['keys'] }}"

- name: Write ssh public key files
  copy:
    content: "{{ item.public }}"
    dest: "/Users/{{ ansible_user_id }}/.ssh/{{ item.name }}.pub"
    mode: 0644
  when: item.public is defined
  with_items: "{{ ssh['keys'] }}"
