---

- name: Install pyenv
  homebrew:
    name: pyenv
    state: present
  when: pyenv_install

- name: Ensure pyenv .bash_profile block is present
  blockinfile:
    marker: "# {mark} MacOSa managed block pyenv"
    dest: "/Users/{{ ansible_user_id }}/.bash_profile"
    create: yes
    block: |
      eval "$(pyenv init -)"
    state: present
  when: pyenv_install

- name: Ensure pyenv .bash_profile block is not present
  blockinfile:
    marker: "# {mark} MacOSa managed block pyenv"
    dest: "/Users/{{ ansible_user_id }}/.bash_profile"
    create: yes
    block: |
      eval "$(pyenv init -)"
    state: absent
  when: not pyenv_install

- name: Install Python Packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_packages }}"
