---

- name: Get current default browser
  shell: "{{ playbook_dir }}/bin/defaultbrowser"
  register: "current_default_browser"
  changed_when: false

- name: Set default browser
  shell: "{{ playbook_dir }}/bin/defaultbrowser -set {{ default_browser }}"
  when: "default_browser not in current_default_browser.stdout"
