#!/bin/bash

echo "Executing pre-commit hook"
files=`git diff --cached --name-only && git diff --name-only`
for f in `echo $files | grep 'vault\.yml$'`; do
  if ! cat $f | grep '^\$ANSIBLE_VAULT' &>/dev/null; then
    echo "ERROR: Unencrypted vault.yml file found: $f"
    echo "       Not going ahead with the commit"
    exit 1
  fi
done
