---

- name: restart dock
  command: >
    killall -HUP Dock

- name: restart systemuiserver
  command: >
    killall -HUP SystemUIServer

- name: logout
  command: >
    touch {{ playbook_dir }}/.logout